apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttyd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttyd
  template:
    metadata:
      labels:
        app: ttyd
    spec:
      containers:
      - name: ttyd
        image: tsl0922/ttyd
        args: ["-p", "7681", "/bin/bash"]
        ports:
        - containerPort: 7681
---
apiVersion: v1
kind: Service
metadata:
  name: ttyd
spec:
  type: NodePort
  ports:
  - port: 7681
    targetPort: 7681
    nodePort: 30001
  selector:
    app: ttyd